default:
  image: python:3.10
  before_script:
  - pip install -U pip

stages:
  - test
  - build

.base_test:
  stage: test
  environment:
    PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple/
  script:
  - pip install -U tox -i $PIP_INDEX_URL
  - tox -e py -i $PIP_INDEX_URL

test:
  image: python:${PYTHONVERSION}
  parallel:
    matrix:
    - PYTHONVERSION:
      - "3.10"
      - "3.11"
  extends:
  - .base_test

test:lint:
  stage: test
  environment:
    PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple/
  script:
  - pip install -U tox -i $PIP_INDEX_URL
  - tox -e isort -i $PIP_INDEX_URL
  - tox -e pylint -i $PIP_INDEX_URL

build:spiderkeeper:
  stage: build
  only:
    variables:
    - $REGISTRY_USER
    - $REGISTRY_PASSWORD
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot

  before_script:
  - export IMAGE_NAME=crawlerstack-spiderkeeper
  - export VERSION=v3.2.0
  - export VERIFY_REGISTRY=false
  - export REGISTRY=docker-private.zncdata.net
  - export TAG=${IMAGE_NAME}:${VERSION}
  - echo $REGISTRY
  - echo $VERIFY_REGISTRY
  - echo $REGISTRY_USER
  - echo $REGISTRY_PASSWORD
  - echo $TAG
  - buildah info
  - echo "$REGISTRY_PASSWORD" | buildah login --tls-verify=${VERIFY_REGISTRY} -u "$REGISTRY_USER" --password-stdin ${REGISTRY}
  - cd crawlerstack-spiderkeeper

  script:
  - buildah build --jobs=2 --tls-verify=${VERIFY_REGISTRY} --platform=linux/arm64,linux/amd64 --manifest="$TAG" .
  - buildah images
  - buildah manifest inspect "$TAG"
  - buildah manifest push --all --tls-verify=${VERIFY_REGISTRY} $TAG docker://${REGISTRY}/${TAG}

