version: "3.7"

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: always
    container_name: 'rabbitmq'
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    networks:
      - app

  mysql:
    image: 'mysql:8.0.16'
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Shanghai
    networks:
      - app

networks:
  app:
    external: true