version: "3.7"
services:
  app:
    image: crawlerstack-spiderkeeper:latest
    volumes:
      - ${PWD}/settings.local.yml:/usr/local/etc/SPIDERKEEPER/server/settings.yml:ro
      - /temp/spiderkeeper:/tmp/spiderkeeper
    entrypoint: [ "crawlerstack_spiderkeeper_server" ]
    command: [ "api", "-h", "0.0.0.0", "-p", "8080" ]
    container_name: crawlerstack-spiderkeeper-server
    ports:
      - "8083:8080"
    logging:
      options:
        max-size: "200M"
        max-file: "3"
    networks:
      - app

networks:
  app:
    external: true
