"""update filearchive model

Revision ID: 39ec906ccd00
Revises: b50671c9ff01
Create Date: 2023-03-07 15:18:59.735564

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39ec906ccd00'
down_revision = 'b50671c9ff01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_archive', 'expired_time',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_comment='过期时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_archive', 'expired_time',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_comment='过期时间',
               existing_nullable=True)
    # ### end Alembic commands ###
