"""update task model

Revision ID: b50671c9ff01
Revises: de84e1f057b1
Create Date: 2023-03-06 14:22:32.370933

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b50671c9ff01'
down_revision = 'de84e1f057b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('snapshot_enable', sa.Boolean(), nullable=True, comment='是否开启快照'))
    op.add_column('job', sa.Column('snapshot_server_id', sa.Integer(), nullable=True, comment='快照服务id'))
    op.create_foreign_key(None, 'job', 'storage_server', ['snapshot_server_id'], ['id'], ondelete='SET NULL')
    op.add_column('task', sa.Column('task_status', sa.Integer(), nullable=True, comment='任务状态'))
    op.add_column('task', sa.Column('consume_status', sa.Integer(), nullable=True, comment='消费状态'))
    op.drop_column('task', 'status')
    op.add_column('task_detail', sa.Column('snapshot_count', sa.Integer(), nullable=False, comment='写入快照数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_detail', 'snapshot_count')
    op.add_column('task', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='任务状态'))
    op.drop_column('task', 'consume_status')
    op.drop_column('task', 'task_status')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'snapshot_server_id')
    op.drop_column('job', 'snapshot_enable')
    # ### end Alembic commands ###
