"""add file archive

Revision ID: de84e1f057b1
Revises: 4d084ca23efa
Create Date: 2023-02-20 15:26:03.265125

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de84e1f057b1'
down_revision = '4d084ca23efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_archive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('local_path', sa.String(length=200), nullable=False, comment='本地文件路径'),
    sa.Column('key', sa.String(length=200), nullable=False, comment='s3文件key'),
    sa.Column('storage_name', sa.String(length=100), nullable=False, comment='存储名称'),
    sa.Column('storage_url', sa.String(length=200), nullable=False, comment='存储目标url'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='文件待上传状态'),
    sa.Column('expired_time', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('task_detail', 'detail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='任务失败值存储')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_detail', 'detail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='任务失败值存储')
    op.drop_table('file_archive')
    # ### end Alembic commands ###
