"""init db

Revision ID: 59f767465f25
Revises: 
Create Date: 2023-01-10 18:14:11.516916

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '59f767465f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='执行器名称'),
    sa.Column('selector', sa.String(length=200), nullable=False, comment='自定义选择器'),
    sa.Column('url', sa.String(length=200), nullable=False, comment='api url'),
    sa.Column('type', sa.String(length=200), nullable=False, comment='类型'),
    sa.Column('status', sa.Integer(), nullable=True, comment='在线或离线'),
    sa.Column('memory', sa.Integer(), nullable=False, comment='内存G'),
    sa.Column('cpu', sa.Integer(), nullable=False, comment='cpu占用%'),
    sa.Column('task_count', sa.Integer(), nullable=False, comment='任务个数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='任务名称'),
    sa.Column('url', sa.String(length=200), nullable=False, comment='任务调度位置'),
    sa.Column('type', sa.String(length=200), nullable=False, comment='任务类型'),
    sa.Column('status', sa.Integer(), nullable=True, comment='任务状态'),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=200), nullable=False, comment='容器ID'),
    sa.Column('task_start_time', sa.DateTime(), nullable=True, comment='任务创建时间'),
    sa.Column('task_end_time', sa.DateTime(), nullable=True, comment='任务结束时间'),
    sa.ForeignKeyConstraint(['executor_id'], ['executor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('executor')
    # ### end Alembic commands ###
