"""add Executor field expired_time

Revision ID: a122aa657f96
Revises: 59f767465f25
Create Date: 2023-03-22 13:38:01.735782

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a122aa657f96'
down_revision = '59f767465f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('expired_time', sa.BigInteger(), nullable=True, comment='过期时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor', 'expired_time')
    # ### end Alembic commands ###
