"""update task model

Revision ID: a272926f6ecf
Revises: a122aa657f96
Create Date: 2023-05-06 15:42:20.006576

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a272926f6ecf'
down_revision = 'a122aa657f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('job_id', sa.Integer(), nullable=False, comment='job id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'job_id')
    # ### end Alembic commands ###
