"""init

Revision ID: 17feeb1da886
Revises: 
Create Date: 2020-07-27 18:22:48.031747

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "17feeb1da886"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
