"""init_table

Revision ID: 69c2d2e2a2af
Revises: 17feeb1da886
Create Date: 2022-02-25 15:39:59.325037

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '69c2d2e2a2af'
down_revision = '17feeb1da886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'audit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('datetime', sa.DateTime(), nullable=True),
        sa.Column('url', sa.String(length=300), nullable=True, comment='URL'),
        sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP 方法'),
        sa.Column('client', sa.String(length=150), nullable=True, comment='客户端地址'),
        sa.Column('detail', sa.Text(), nullable=True, comment='详细内容'),
        sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
                    sa.Column('slug', sa.String(length=200), nullable=False),
                    sa.Column('desc', sa.Text(), nullable=True, comment='项目描述'),
                    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
                    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    op.create_table('server',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=45), nullable=True, comment='服务器名称'),
                    sa.Column('type', sa.String(length=45), nullable=True, comment='服务器类型'),
                    sa.Column('uri', sa.String(length=100), nullable=True, comment='URI'),
                    sa.Column('enable', sa.Boolean(), nullable=True, comment='是否启用配置'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('artifact',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
                    sa.Column('filename', sa.String(length=200), nullable=True, comment='文件名称'),
                    sa.Column('interpreter', sa.String(length=500), nullable=True, comment='解释器'),
                    sa.Column('tag', sa.String(length=100), nullable=True, comment='Tag'),
                    sa.Column('execute_path', sa.String(length=100), nullable=True, comment='执行路径'),
                    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('job',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('create_time', sa.DateTime(), nullable=True),
                    sa.Column('update_time', sa.DateTime(), nullable=True),
                    sa.Column('cmdline', sa.String(length=200), nullable=True, comment='执行命令'),
                    sa.Column('storage_enable', sa.Boolean(), nullable=True, comment='是否开启存储'),
                    sa.Column('artifact_id', sa.Integer(), nullable=True),
                    sa.Column('server_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('storage',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('create_time', sa.DateTime(), nullable=True, comment='开始时间'),
                    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
                    sa.Column('count', sa.Integer(), nullable=True, comment='导出数据量'),
                    sa.Column('status', sa.Integer(), nullable=True, comment='存储任务状态'),
                    sa.Column('detail', sa.String(length=1000), nullable=True, comment='存储任务详情，失败后的值可以存在这里，便于诊断'),
                    sa.Column('job_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
                    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
                    sa.Column('status', sa.Integer(), nullable=True, comment='任务状态'),
                    sa.Column('item_count', sa.Integer(), nullable=True, comment='写入数据数量'),
                    sa.Column('detail', sa.Text(), nullable=True, comment='任务详情'),
                    sa.Column('container_id', sa.String(length=120), nullable=True, comment='容器 ID'),
                    sa.Column('job_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('storage')
    op.drop_table('job')
    op.drop_table('artifact')
    op.drop_table('server')
    op.drop_table('project')
    op.drop_table('audit')
    # ### end Alembic commands ###
